---
- name: copy
  hosts: test-servers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "copy file"
      copy: src=/user/Documents/webpage/page.php dest=/var/files/page.php